interface ZIF_AWC_OVERVIEW_CONSTANTS
  public .


  constants C_LIFECYCLE_DOMAIN type DDOBJNAME value '/SCMTMS/TOR_LC_STATUS' ##NO_TEXT.
  constants C_EXECUTION_DOMAIN type DDOBJNAME value '/SCMTMS/TOR_EXECUTION_STATUS' ##NO_TEXT.
  constants C_DELIVERY_DOMAIN type DDOBJNAME value '/SCMTMS/DELIVERY_STATUS' ##NO_TEXT.
  constants C_CONFIRMATION_DOMAIN type DDOBJNAME value '/SCMTMS/TOR_CONFIRM_STATUS' ##NO_TEXT.
  constants C_SUBCONTRACTING_DOMAIN type DDOBJNAME value '/SCMTMS/TOR_SUBCONTR_STATUS' ##NO_TEXT.
endinterface.
